spring:
  data:
    mongodb:
      username: developer
      password: dev_pass
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090

